services:
  - type: web
    name: api-registry-backend
    env: node
    buildCommand: yarn --frozen-lockfile install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
